services:
  pgvector:
    image: pgvector/pgvector:pg18
    container_name: pgvector
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=user # 用户名
      - POSTGRES_PASSWORD=password # 密码
    networks:
      - qingchun-network

networks:
  qingchun-network:
    external: true