services:
  nginx-ui:
    image: uozi/nginx-ui:latest
    container_name: nginx-ui
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - './conf/nginx:/etc/nginx'
      - './conf/nginx-ui:/etc/nginx-ui'
      - './logs:/var/log/nginx'
      - './var/www:/var/www'
      - '/var/run/docker.sock:/var/run/docker.sock'