services:
  redis:
    image: redis:8.6.2
    container_name: redis
    restart: always
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./logs:/logs
    networks:
      - qingchun-network

networks:
  qingchun-network:
    external: true