services:
  beszel-hub:
    image: henrygd/beszel:latest
    container_name: beszel-hub
    restart: always
    environment:
    - 'TZ=Asia/Shanghai'
    - 'APP_URL=http://localhost:8090'
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - qingchun-network

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: always
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - 'TZ=Asia/Shanghai'
    - 'LISTEN=/beszel_socket/beszel.sock'
    - 'HUB_URL=http://localhost:8090'
    - 'TOKEN=令牌'
    - 'KEY=密钥'

networks:
  qingchun-network:
    external: true
